#!/usr/bin/env python
'''
    Original version by Tim Savannah. Released to Public Domain
'''

import sys

from cmp_version import cmp_version


if __name__ == '__main__':

    if '--help' in sys.argv or len(sys.argv) != 3:
        sys.stderr.write('''Usage: cmp-version [version1] [version2]
  Compares two provided version strings

 Prints "0" if the two versions are equal (even if the strings aren't equal, like 1.0 vs 1.0.0)
 Prints "1" if version1 is newer/greater than version2
 Prints "-1" if version1 is older/less than version2
''')
        sys.exit(1)

    sys.stdout.write("%d\n" %(cmp_version(sys.argv[1], sys.argv[2]),))
